package revisao;

import java.util.Vector;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fabiana
 */
public class compraGUI extends javax.swing.JPanel {

    private Produto produtoSelecionado;
    private ModeloTabelaCompra carrinhoComprasTab;
    private double precoCompra;

    public compraGUI() {

        meuInitComponents();
        precoCompra = 0.0;
    }

    private void meuInitComponents() {
        this.carrinhoComprasTab = new ModeloTabelaCompra();

        TabelaCC.setModel(carrinhoComprasTab);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        estoqBt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalTxt = new javax.swing.JLabel();
        CodTxt = new javax.swing.JTextField();
        addBt = new javax.swing.JButton();
        NomeTxt = new javax.swing.JTextField();
        QuantTxt = new javax.swing.JTextField();
        PrecoUnitTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaCC = new javax.swing.JTable();
        removeBt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        finBt = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Nome");

        estoqBt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        estoqBt.setText("Estoque");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Quantidade");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Valor Total :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Preço Unit");

        totalTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalTxt.setText("R$ 0,00");

        CodTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CodTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodTxtActionPerformed(evt);
            }
        });
        CodTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CodTxtKeyTyped(evt);
            }
        });

        addBt.setText("Add Produto");
        addBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtMouseClicked(evt);
            }
        });
        addBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtActionPerformed(evt);
            }
        });

        NomeTxt.setEditable(false);
        NomeTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        QuantTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        QuantTxt.setText("1");
        QuantTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantTxtActionPerformed(evt);
            }
        });
        QuantTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                QuantTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                QuantTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QuantTxtKeyTyped(evt);
            }
        });

        PrecoUnitTxt.setEditable(false);
        PrecoUnitTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        TabelaCC.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TabelaCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelaCC);

        removeBt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        removeBt.setText("Remover");
        removeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Código");

        finBt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        finBt.setText("Finalizar");
        finBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finBt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(CodTxt)
                            .addComponent(NomeTxt)
                            .addComponent(QuantTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(PrecoUnitTxt)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(addBt)
                                .addGap(12, 12, 12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalTxt)))))
                .addGap(18, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estoqBt)
                    .addComponent(removeBt))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CodTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(QuantTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PrecoUnitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(finBt)
                                .addGap(29, 29, 29)
                                .addComponent(addBt))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(totalTxt))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(removeBt)
                        .addGap(84, 84, 84)
                        .addComponent(estoqBt)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CodTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodTxtActionPerformed

    }//GEN-LAST:event_CodTxtActionPerformed

    private void CodTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodTxtKeyTyped
        if (evt.getKeyChar() == '\n') {

            if (!CodTxt.getText().isEmpty()) {
                try {
                    int cod = Integer.parseInt(CodTxt.getText());
                    Produto consultado = FakeBD.conProdCod(cod);

                    if (consultado != null) {
                        NomeTxt.setText(consultado.getNome());
                        PrecoUnitTxt.setText(consultado.getPreco() + "");
                        QuantTxt.setEnabled(true);

                    } else {
                        JOptionPane.showMessageDialog(null, "Produto não cadastrado", "código", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "O código deve ser um valor númerico", "erro no codigo", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_CodTxtKeyTyped

    private void QuantTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantTxtActionPerformed
        //   //calcula o preço parcial dos produtos

        if (!QuantTxt.getText().isEmpty()) {
            try {
                int quantidade = Integer.parseInt(QuantTxt.getText());
                double parc = produtoSelecionado.getPreco() * quantidade;
                PrecoUnitTxt.setText(String.format("%.2f", parc));

            } catch (NumberFormatException ex) {
                PrecoUnitTxt.setText("N/A");
            }
        } else {
            PrecoUnitTxt.setText("N/A");
        }
    }//GEN-LAST:event_QuantTxtActionPerformed

    private void removeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtActionPerformed

        int linha = TabelaCC.getSelectedRow();
        if (linha > -1) {
            int op = JOptionPane.showConfirmDialog(null, "Deseja remover o produto selecionado?",
                    "Confirmação de exclusão", JOptionPane.YES_NO_OPTION);
            if (op == JOptionPane.YES_OPTION) {
                String senha = JOptionPane.showInputDialog(null, "Informe a senha do gerente",
                        "operação restrita", JOptionPane.INFORMATION_MESSAGE);
                if (senha != null && senha.equals("ifmg")) {
                    carrinhoComprasTab.removeProdutoCarrinho(linha);
                    atualizaQuantidades();
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "primeiro é necessário selecionar"
                    + " algum produto", "selecionar!!!", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_removeBtActionPerformed

    private void addBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtActionPerformed
        if (produtoSelecionado != null && !PrecoUnitTxt.getText().equals("N/A")) {

            int quantidade = Integer.parseInt(QuantTxt.getText());

            if (quantidade <= produtoSelecionado.getQnt()) {

                Produto vendido = new Produto(produtoSelecionado.getCod(), produtoSelecionado.getNome(), produtoSelecionado.getPreco(), quantidade);

                //produtoSelecionado.setQnt(produtoSelecionado.getQnt() - quantidade);
                precoCompra += produtoSelecionado.getPreco() * quantidade;
                totalTxt.setText(String.format("%.2f", precoCompra));

                CodTxt.setText("");
                QuantTxt.setText("");
                PrecoUnitTxt.setText("");
                produtoSelecionado = null;
                QuantTxt.setEnabled(false);
                NomeTxt.setText("");

                this.carrinhoComprasTab.addNovoProduto(vendido);
                TabelaCC.updateUI();

            } else {
                JOptionPane.showMessageDialog(null, "Não há quantidade sufuciente para realizar a venda deste produto",
                        "quantidade insuficiente", JOptionPane.INFORMATION_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "A quantidade de produtos informada"
                    + "deve ser um valor numérico", "entrada de quantidade inválida", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addBtActionPerformed
    public void atualizaQuantidades() {
        TabelaCC.updateUI();

        double preco = carrinhoComprasTab.calculaPrecoParcialCompra();

        totalTxt.setText(String.format("%.2f", preco));
    }
    private void addBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtMouseClicked


    }//GEN-LAST:event_addBtMouseClicked
    private boolean verificaQuantidades() {
        Vector<Produto> produtos = carrinhoComprasTab.produtosCarrinho();

        for (int i = 0; i < produtos.size(); i++) {
            Produto estoque = FakeBD.conProdCod(produtos.get(i).getCod());
            if (produtos.get(i).getQnt() > estoque.getQnt()) {
                JOptionPane.showMessageDialog(null, "A quantidade do produto" + estoque.getNome() + "não é suficiente para real. a venda", "Quantidade insuficiente", JOptionPane.INFORMATION_MESSAGE);
                return false;
            }
        }
        return true;
    }
    private void finBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finBtActionPerformed

        if (verificaQuantidades() == true) {
            Vector<Produto> produtos = carrinhoComprasTab.produtosCarrinho();

            for (int i = 0; i < produtos.size(); i++) {
                Produto estoque = FakeBD.conProdCod(produtos.get(i).getCod());
                estoque.setQnt(estoque.getQnt() - produtos.get(i).getQnt());

            }
            precoCompra = 0.0;
            totalTxt.setText("0.0");

            carrinhoComprasTab.limpaCarrinho();
            TabelaCC.updateUI();
        }


    }//GEN-LAST:event_finBtActionPerformed

    private void QuantTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantTxtKeyPressed

    }//GEN-LAST:event_QuantTxtKeyPressed

    private void QuantTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantTxtKeyReleased

        if (QuantTxt.getText().isEmpty()) {
            try {
                int qtde = Integer.parseInt(QuantTxt.getText());

                double parc = produtoSelecionado.getPreco() * qtde;
                PrecoUnitTxt.setText(String.format("%.2f", parc));
            } catch (NumberFormatException ex) {
                PrecoUnitTxt.setText("N/A");
            }
        } else {
            PrecoUnitTxt.setText("N/A");

        }
    }//GEN-LAST:event_QuantTxtKeyReleased

    private void QuantTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantTxtKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodTxt;
    private javax.swing.JTextField NomeTxt;
    private javax.swing.JTextField PrecoUnitTxt;
    private javax.swing.JTextField QuantTxt;
    private javax.swing.JTable TabelaCC;
    private javax.swing.JButton addBt;
    private javax.swing.JButton estoqBt;
    private javax.swing.JButton finBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeBt;
    private javax.swing.JLabel totalTxt;
    // End of variables declaration//GEN-END:variables
}
